version: '2'
services:
  nginx:
    container_name: nginx
    image: nginx:1.13.2
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - web
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    ports:
      - "80:80"

    restart: always

  web:
    container_name: web
    image: spring-boot-mongodb:latest
    volumes:
      - ./config:/config
      - ./log:/log
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    restart: always